# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: webapp
summary: Dev environment for identityProvider
description: Dev environment for identityProvider
templatePath: ../infra/main.bicep
runner: bicep
