# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: webapp
summary: Dev environment for identityProvider
description: Dev environment for identityProvider
templatePath: main.bicep
runner: bicep
parameters:
  - id: environmentName
    name: environmentName
    type: string
    default: dev
  - id: identityProviderExists
    name: identityProviderExists
    type: string
    default: SERVICE_IDENTITY_PROVIDER_RESOURCE_EXISTS=false
  
