apiVersion: v1
kind: Service
metadata:
  name: {{ include "identityprovider.fullname" . }}
  labels:
    {{- include "identityprovider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 5001
      protocol: TCP
      name: https
  selector:
    {{- include "identityprovider.selectorLabels" . | nindent 4 }}
