name: Deploy ASP.NET Core app to Azure Web App

on:
  workflow_dispatch:
    inputs:
      AZURE_WEBAPP_NAME:
        description: 'Azure Web App Name'
        required: true
        default: 'identityServerApp'

env:
  AZURE_WEBAPP_NAME: ${{ inputs.AZURE_WEBAPP_NAME }}    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.x'             # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v4
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore /src/IdentityServer/IdentityServer.csproj
          dotnet build /src/IdentityServer/IdentityServer.csproj --configuration Release
          dotnet publish /src/IdentityServer/IdentityServer.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/IdentityServer' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/IdentityServer' 

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples