name: Identity Provider CI/CD
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - dependabot/*
    
permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'

      - name: Build Idetity Provider
        run: |
          dotnet restore 
          dotnet build --configuration Release --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'

      - name: Test Idetity Provider
        run: |
          dotnet test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Provision Infrastructure and Deploy Application
        run: azd up --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

      - name: Teardown Infrastructure
        run: azd down --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
